export const STRINGS = {
  // Greetings
  MORNING: 'Good morning',
  AFTERNOON: 'Good afternoon',
  EVENING: 'Good evening',
  EMOJI_MORNING: '☀️',
  NO_ROUTINES_TODAY: 'No routines today',
  EMOJI_AFTERNOON: '🌤',
  EMOJI_EVENING: '🌙',
  EDIT_EXPENSE: 'Edit Expense',
  ADD_TO_TODAY: 'Add to Today',
  REMOVE_FROM_TODAY: 'Remove from Today',
  COMPLETED_TODAY: 'Completed today',
  SUBTASK: 'subtask',
  EXPENSES: 'Expenses',
  FOCUS_TASK: 'What are you focusing on?',
  FOCUS_COMMITMENT_LABEL: 'I will finish...',
  FOCUS_COMMITMENT_PLACEHOLDER: 'e.g. the PR review and leave comments',
  FOCUS_MUSIC_LABEL: 'Music (optional)',
  FOCUS_MUSIC_PLACEHOLDER: 'Paste a YouTube, SoundCloud, or Vimeo link...',
  FOCUS_DURATION: 'Duration',
  FOCUS_CUSTOM: 'Custom',
  FOCUS_CUSTOM_PLACEHOLDER: 'Minutes',
  FOCUS_START: 'Start Focus',
  FOCUS_DRIFTED: 'I drifted',
  FOCUS_IM_BACK: "I'm back",
  FOCUS_DONE: 'Done',
  FOCUS_DRIFTS: 'drifts',
  FOCUS_SUBTITLE: "One thing. Full attention. Let's go.",
  FOCUS_FINISHED_TITLE: 'Did you finish what you committed to?',
  FOCUS_FINISHED_SUBTITLE: 'Be honest with yourself.',
  FOCUS_YES_FINISHED: '✅ Yes, I finished',
  FOCUS_NEED_MORE_TIME: '⏱ Need more time',
  FOCUS_GOT_PULLED_AWAY: 'Got pulled away',
  FOCUS_GREAT_WORK: 'You did it.',
  FOCUS_NO_JUDGMENT: 'No judgment.',
  FOCUS_TRY_AGAIN_LATER: 'Life happens. Come back when you can.',
  FOCUS_TRY_AGAIN: 'Try again',
  FOCUS_MARK_DONE_ANYWAY: 'Mark as done anyway',
  FOCUS_BACK_TO_TODAY: 'Back to Today',
  NO_EXPENSES: 'No Expenses',
  TRANSACTIONS: 'Transactions',
  LOG_EXPENSE: 'Log Expense',
  LOG_EXPENSE_SUB: 'Track what you spent',
  LOG_REFUND: 'Log Refund',
  LOG_REFUND_SUB: 'Track money coming back',
  LOG_SPLITWISE: 'Log Split',
  LOG_SPLITWISE_SUB: 'Track shared expenses',
  LOG_SUBSCRIPTION: 'Log Subscription',
  LOG_SUBSCRIPTION_SUB: 'Track recurring charges',
  EXPENSE_LOGGED: 'Logged!',
  LOG_ANOTHER: 'Log another',
  PUTS_YOU_AT: 'Puts you at',
  OVER_BUDGET: 'over budget',
  KEEPS_YOU: 'Keeps you',
  UNDER_BUDGET: 'under budget',
  FAILED_TO_SAVE: 'Failed to save. Try again.',
  REFUND_SAVED: 'Refund logged. Atlas will flag if not received by',
  THEY_OWE_ME: 'They owe me',
  I_OWE_THEM: 'I owe them',
  DIRECTION: 'Direction',
  MONTHLY: 'Monthly',
  YEARLY: 'Yearly',
  ON_THE: 'on the',
  TH: 'th',
  CATEGORY: 'Category',
  DONE: 'Done',
  // Section headers
  ALL_TASKS: 'All Tasks',
  WORK: 'Work',
  PERSONAL: 'Personal',
  OVERDUE: 'Overdue',
  SPRINT: 'Sprint',
  FOLLOWUPS: 'Follow-ups',
  MEETING_PREP: 'Meeting Prep',
  MISC: 'Misc',
  SUBTASKS: 'Subtasks',
  CALENDAR: 'Calendar',
  LINK_TO: 'Link to',
  WHAT_ARE_YOU_LOGGING: 'What are you logging?',
  LOG_SUBTITLE: 'Track every dollar in and out.',

  SPLITWISE_SAVED: 'Split logged.',
  SUBSCRIPTION_SAVED: 'Subscription saved.',
  // Empty states
  NO_WORK_TODAY: 'No work tasks today.',
  NO_PERSONAL_TODAY: 'Nothing personal due today.',
  NO_EVENTS_TODAY: 'No events today',
  NO_TASKS_FOR_DAY: 'No tasks for this day',

  // Actions
  ADD_TASK: 'Add Task',
  ADD_EVENT: 'Add Event',
  ADD_WORK_TASK: '+ Add Work Task',
  ADD_PERSONAL_TASK: '+ Add Personal Task',
  ADD_SUBTASK: '+ Add Subtask',
  ADD_FOR_DAY: '+ Add Task for This Day',
  MARK_DONE: 'Mark Done',
  MARKED_DONE: 'Marked done',
  MOVE_TO_TODAY: 'Move to Today',
  DELETE: 'Delete',
  EDIT: 'Edit',
  UNDO: 'Undo',
  CANCEL: 'Cancel',
  BACK: '← Back',

  // Fields
  MUST_TODAY: 'Must today?',
  WHAT_NEEDS_DONE: 'What needs to be done?',
  SEARCH_LINK: 'Search goal / project / milestone...',
  SEARCH_TASKS: 'Search tasks...',

  // Filters
  ALL_TYPES: 'All types',
  ALL_PRIORITIES: 'All priorities',

  // Misc
  AVOIDING: 'Avoiding',
  PUSHED_TIMES: (n: number) => `Pushed ${n} times`,

  // AI
  AI_PROMPT_PREFIX:
    'You are Atlas, a personal productivity assistant. Give ONE short sentence summarizing today.',

  MUST: 'Must',
  RECURRING: 'Recurring',
  COLLAPSE: 'Collapse',
  EXPAND: 'Expand',

  TYPE: 'Type',
  PRIORITY: 'Priority',
  DUE_DATE: 'Due date',
  CADENCE: 'Cadence',
  EVENT_TIME: 'Time',
  EVENT_DURATION: 'Duration (min)',
  NOTES: 'Notes',
  CLEAR: 'Clear',
  ADD: 'Add',
  SUBTASKS_DONE: 'subtasks done',
  NOTES_PLACEHOLDER: 'Add notes...',
  CONFIRM_DELETE: 'Tap again to confirm',
  DELETE_WARNING: 'This will permanently delete the task and all subtasks.',
  NO_DATE: 'No date',
  MORE_OPTIONS: 'More options',
  LESS_OPTIONS: 'Less',
  CHECK_BEFORE: 'Check first',
  STILL_LOG: 'Log anyway',
  LOG_IT: 'Log it',
  BUDGETS: 'Budgets',
  EDIT_BUDGETS: 'Edit Budgets',
  NO_ACCOUNTS: 'No accounts added yet.',
  ADD_ACCOUNT: 'Add Account',
  EDIT_ACCOUNT: 'Edit Account',
  ACCOUNTS_INVENTORY: 'Accounts',
  INSTITUTION_NAME: 'Institution name',
  ACCOUNT_TYPE: 'Type',
  LAST_FOUR: 'Last four',
  LABEL_OPTIONAL: 'Label (optional)',
  DUE_DATE_DAY: 'Due date (day of month)',
  DUE: 'due',
  ADD_FINANCE_TASK: 'Add finance task...',
  COMPLETED_TASKS: 'completed',
  REFUND_TRACKER: 'Refunds',
  EMPTY_REFUNDS: 'No pending refunds.',
  RETURNED: 'Returned',
  EXPECTED: 'Expected by',
  SEND_FOLLOW_UP: 'Send follow up',
  RECEIVED: 'Received',
  GAVE_UP: 'Gave up',
  SPLITWISE: 'Splitwise',
  EMPTY_SPLITWISE: 'No outstanding splits.',
  YOU_ARE_OWED: 'They owe you',
  YOU_OWE: 'You owe',
  SEND_REMINDER: 'Send reminder',
  SETTLED: 'Settled',
  SETTLED_THIS_MONTH: 'Settled',
  SUBSCRIPTIONS: 'Subscriptions',
  EMPTY_SUBSCRIPTIONS: 'No active subscriptions.',
  RENEWING_SOON: 'Renewing soon',
  RENEWS_IN: 'Renews in',
  RENEWS_DAY: 'Renews day',
  DAYS: 'days',
  KEEP: 'Keep',
  CANCEL_SUB: 'Cancel',
  COPY_MESSAGE: 'Copy message',
  COPY_TO_CLIPBOARD: 'Copy',
  DISMISS: 'Dismiss',
  SAVE_CHANGES: 'Save Changes',
  // PRIORITY
  MEDIUM: 'medium',
  LOW: 'low',
  FIELD_AMOUNT: 'Amount',
  FIELD_NOTE: 'Note',
  FIELD_NAME: 'Name',
  FIELD_WHO: 'Who',
  FIELD_WHAT_FOR: 'What for',
  FIELD_WHAT_RETURNED: 'What was returned',
  FIELD_EXPECTED_BY: 'Expected by',
  FIELD_RENEWS: 'Renews',
  PH_AMOUNT: '0.00',
  PH_NOTE: 'Optional note',
  PH_PERSON: 'Name',
  PH_SPLIT_DESC: 'Dinner, Uber...',
  PH_REFUND_DESC: 'Amazon return, insurance...',
  PH_SUB_NAME: 'Netflix, Spotify...',
  // STRINGS
  TASKS: 'Tasks',
  TOTAL: 'Total',
  DUE_TODAY: 'Due today',
  SELECTED: 'selected',
  NO_TASKS_FOUND: 'No tasks match your filters.',
  CLEAR_FILTERS: 'Clear filters',
  CLEAR_ALL: 'Clear all',
  MARK_TODO: 'Mark as todo',
  SELECT: 'Select',
  TODAY: 'Today',
  FILTER: 'filter',
  GROUP_BY: 'Group by',
  PLAN: 'Plan',
  YOUR_GOALS: 'Your Goals',
  ACTIVE: 'active',
  COMPLETED: 'completed',
  NEW_GOAL: 'New Goal',
  EDIT_GOAL: 'Edit Goal',
  DAILY_MANTRA: 'Daily Mantra',
  MANTRA_PLACEHOLDER: 'What do you want to remind yourself every day?',
  MANTRA_EMPTY: 'Tap to set your daily mantra...',
  GOALS_EMPTY: 'What do you want to achieve this year?',
  GOALS_EMPTY_SUB:
    'Set a goal — something real, something that matters to you.',
  COMPLETED_GOALS: 'Completed Goals',
  DROPPED_GOALS: 'Dropped',
  WHAT_IS_THE_GOAL: "What's the goal?",
  GOAL_PLACEHOLDER: 'Get AWS certified, Run a marathon...',
  GOAL_NAME_REQUIRED: 'Give your goal a name',
  AI_EVALUATING: 'Evaluating...',
  AREA: 'Area',

  NO_FINANCE_TASKS: 'No finance tasks yet.',
  FINANCE_TODOS: 'Finance Tasks',

  AFFIRMATION: 'Affirmation',
  AFFIRMATION_PLACEHOLDER: 'I am becoming someone who...',
  DEADLINE_OPTIONAL: 'Deadline (optional)',
  DROP_GOAL: 'Drop',
  MARK_GOAL_DONE: 'Mark Goal Done',
  BACK_TO_GOALS: 'Back to Goals',
  GOAL_NOT_FOUND: 'Goal not found',
  MILESTONES: 'milestones',
  ADD_MILESTONE: 'Add Milestone',
  MILESTONES_EMPTY: 'Break this goal into milestones',
  MILESTONE_PLACEHOLDER: 'Milestone name...',
  ADD_TASK_PLACEHOLDER: 'Add task...',
  LINKED_PROJECTS: 'Linked Projects',
  LINK_PROJECT: 'Link Project',
  NO_LINKED_PROJECTS: 'No projects linked yet',
  LINKED_ROADMAPS: 'Linked Roadmaps',
  LINK_ROADMAP: 'Link Roadmap',
  LEARNING_TODAY: 'Learning Today',
  GROWTH_CALENDAR: '/growth/calendar',
  NO_LINKED_ROADMAPS: 'No roadmaps linked yet',
  ADD_PROJECT: '+ Project',
  ADD_ROADMAP: '+ Roadmap',
  LINK_EXISTING: 'Link existing:',
  LINK_EXISTING_PROJECT: 'Link an existing project:',
  LINK_EXISTING_ROADMAP: 'Link an existing roadmap:',
  NEW_PROJECT_NAME: 'New project name...',
  NEW_ROADMAP_NAME: 'New roadmap name...',
  OR_CREATE_NEW: 'or create new',
  CREATE: 'Create',
  VIEW: 'View',
  SAVE: 'Save',
  ALL: 'all',
  LOG: 'Log',

  DAYS_LEFT: 'days left',
  STILL_YOURS: 'still yours',
  OF: 'of',
  SPENT: 'spent',
  SPENT_THIS_MONTH: 'Spent this month',
  SET_ASIDE: 'Set aside',
  GOAL_REACHED: 'Goal reached ✓',
  GOAL: 'Goal',

  NEEDS_ATTENTION: 'Needs attention',
  OVER: 'Over',
  RECENT_EXPENSES: 'Recent expenses',
  CONFIRM_DELETE_EXPENSE: 'Remove this expense?',
  YES: 'Yes',
  NO: 'No',
  STEP_TITLE: 'Step title',
  DESCRIPTION_OPTIONAL: 'Description (optional)',
  THEME: 'Theme',
  GENERAL: 'General',
  DONE_TODAY: 'Done today',
  ALL_CADENCES: 'All cadences',
  SEARCH_ROUTINES: 'Search routines...',
  NO_ROUTINES_FOUND: 'No routines match your filters.',
  ROUTINE_NAME_PLACEHOLDER: 'Morning routine, AWS prep...',
  REQUIRED: 'Required',
  CREATE_AND_EDIT: 'Create & Edit',
  TITLE: 'Title',
  NEW_ROUTINE: 'New Routine',
  WHEN_THIS_IS_DONE: 'When this is done',
  NAV_DAILY: 'Daily',
  NAV_TODAY: 'Today',
  NAV_TASKS: 'Tasks',
  NAV_FOCUS: 'Focus',
  NAV_INBOX: 'Inbox',
  NAV_ROUTINES: 'Routines',
  NAV_PLAN: 'Plan',
  NAV_GOALS: 'Goals',
  NAV_PROJECTS: 'Projects',
  NAV_ROADMAPS: 'Roadmaps',
  NAV_LIFE: 'Life',
  NAV_FINANCE: 'Finance',
  NAV_HEALTH: 'Health & Body',
  NAV_LIVING: 'Living Life',
  NAV_GROWTH: 'Growth',

  HAPPENING_NOW: 'Now',

  ROUTINES: 'Routines',
  ROUTINE_OUTCOME_LABEL: 'What it feels like when done',
  ROUTINE_OUTCOME_PLACEHOLDER: 'Squeaky clean, skin soft...',
  ROUTINE_NEW: 'New Routine',
  ROUTINE_EDIT: 'Edit',
  ROUTINE_RUN: 'Start',
  ROUTINE_STEPS: 'steps',
  ROUTINE_LAST_DONE: 'Last done',
  ROUTINE_NEVER_DONE: 'Never done',
  ROUTINE_DONE: 'Done',
  ROUTINE_SKIP: 'Skip',
  ROUTINE_COMPLETE_TITLE: 'All done!',
  ROUTINE_ADD_SECTION: 'Add section',
  ROUTINE_ADD_STEP: 'Add step',
  ROUTINE_SECTION_NAME_PLACEHOLDER: 'Section name...',
  ROUTINE_STEP_TITLE_PLACEHOLDER: 'Step title...',
  ROUTINE_DELETE_SECTION_CONFIRM: (name: string) =>
    `Delete ${name} and all its steps?`,
  ROUTINE_RESET_CONFIRM: (name: string) =>
    `Reset ${name} to original steps? Your changes will be lost.`,
  ROUTINE_EMPTY: 'No routines yet. Create your first one.',
  ROUTINE_NO_STEPS: 'This routine has no steps. Tap edit to add some.',
  ROUTINE_TRIGGERED_SECTION: 'Triggered Routines',
  ROUTINE_START_TRIGGERED: 'Start triggered routine',
  BACK_TO_ROUTINES: 'Back',
  LEARNING_AREAS: 'Learning Areas',
  NEW_AREA: 'New Area',
  EDIT_AREA: 'Edit Area',
  ADD_AREA: '+ Add Area',
  ADD_LEARNING_ITEM: 'Add Item',
  NO_LEARNING_ITEMS: 'No learning items for this day.',
  LEARNING_ITEM_PLACEHOLDER: 'What will you learn?',
  TOPIC_CONQUERED: 'topic conquered',
  TOPICS_CONQUERED: 'topics conquered',
  BOOK_IN_MIND: 'book in your mind',
  BOOKS_IN_MIND: 'books in your mind',
  CURRENT: 'Current',
  NOT_STARTED: 'Not started',
  BOOKS_REMAINING: 'books to go',
  VIEW_ALL: 'View all',
  AREA_NAME: 'Name',
  AREA_NAME_PLACEHOLDER: 'System Design, Spanish...',
  EMOJI: 'Emoji',
  BOOKS: 'Books',
  ADD_BOOK: 'Add Book',
  EDIT_BOOK: 'Edit Book',
  BOOKS_EMPTY:
    "No books added yet. Start with one you've been meaning to read.",
  READING_NOW: 'Reading Now',
  WANT_TO_READ: 'Want to Read',
  START_READING: 'Start reading',
  BOOK_TITLE: 'Title',
  BOOK_TITLE_PLACEHOLDER: 'Book title...',
  AUTHOR_OPTIONAL: 'Author (optional)',
  STATUS: 'Status',
  NEW_ROADMAP: 'New Roadmap',
  SESSIONS_COMPLETED: 'sessions completed',
  RUNS: 'runs',
  // ─── ADD THESE TO src/features/tasks/constants/strings.ts ────────────────────
  // Paste inside the STRINGS object

  // Reset Mode
  RESET_MODE: 'Reset Mode',
  RESET_READY: "I'm ready",
  RESET_SEE_REALITY: 'See reality check',
  RESET_PICK_ONE: 'Pick one thing',
  RESET_RECOMMIT: 'Recommit',
  RESET_BACK_TO_TODAY: 'Back to Today',
  RESET_DONE_TITLE: "You've got this.",
  RESET_DONE_SUBTITLE:
    'Everything else is secondary. Come back to this when things feel off.',
  RESET_WEEKS_FOCUS: "This week's focus",
  RESET_CTA_SUBTITLE:
    'Things feeling off? Take 5 minutes to breathe, reflect, and recommit.',
  RESET_DUMP_TITLE: "What's weighing on you right now?",
  RESET_DUMP_SUBTITLE: "Don't filter. Just type everything.",
  RESET_DUMP_PLACEHOLDER:
    "Work is overwhelming, I haven't called mom, finances feel out of control...",
  RESET_REALITY_TITLE: "Here's where things actually are.",
  RESET_ONE_TITLE:
    'If you could only fix one thing this week, what would it be?',
  RESET_ONE_PLACEHOLDER: 'Or write your own...',
  RESET_OVERDUE: 'Overdue tasks',
  RESET_BUDGET_USED: 'Budget used',
  RESET_OF_BUDGET: 'of monthly budget',
  RESET_LAST_SLEEP: 'Last sleep logged',
  RESET_ACTIVE_GOALS: 'Active goals',
  RESET_IN_PROGRESS: 'in progress',

  // Breathe
  BREATHE_IN: 'Breathe in...',
  BREATHE_HOLD: 'Hold...',
  BREATHE_OUT: 'Breathe out...',
  BREATHE_MORE_CYCLES: 'more cycles',
  BREATHE_READY: 'Ready when you are',

  // Audit Tab
  AUDIT_LIFE_SCORE: 'Weekly Life Score',
  AUDIT_SCORE_SUBTITLE: 'Based on tasks, finance, health, goals & routines',
  AUDIT_THIS_WEEK: 'This Week',
  AUDIT_FINANCE_PULSE: 'Financial Pulse',
  AUDIT_ACTIVE_GOALS: 'Active Goals',
  AUDIT_YESTERDAY_WINS: "Yesterday's Wins",
  AUDIT_INSIGHT: 'Atlas Insight',
  AUDIT_WEEKS_FOCUS: "This week's focus",
  MORE_COMPLETED: 'more completed',

  // Insight messages (functions)
  INSIGHT_ZERO:
    "You haven't completed any tasks this week. Start with one small thing — momentum builds fast.",
  INSIGHT_LOW: (n: number) =>
    `You've completed ${n} tasks this week. Picking up — keep going.`,
  INSIGHT_GOOD: (n: number) =>
    `Strong week — ${n} tasks done. You're in a good rhythm.`,

  // Finance
  ON_TRACK: 'On track',
  LEFT: 'left',
  SAVED: 'Saved',
  BUDGET: 'Budget',

  // Misc
  NOT_LOGGED: 'Not logged',
  SKIP: 'Skip',
} as const
