import {
  Expense,
  Budget,
  Refund,
  SplitwiseEntry,
  Subscription,
  Account,
  FinanceTodo,
} from '../types/finance.types'
import { getCurrentMonth } from '../utils/dateUtils'

const month = getCurrentMonth()
const uid = '00000000-0000-0000-0000-000000000001'

function id() {
  return crypto.randomUUID()
}
function ts() {
  return new Date().toISOString()
}

export const SEED_BUDGETS: Budget[] = [
  {
    id: id(),
    user_id: uid,
    category: 'rent',
    amount: 120000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'phone',
    amount: 4500,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'internet',
    amount: 6000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'insurance',
    amount: 12000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'food_delivery',
    amount: 15000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'coffee',
    amount: 4000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'shopping',
    amount: 20000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'entertainment',
    amount: 5000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'personal_care',
    amount: 20000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'transport',
    amount: 10000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'investing',
    amount: 20000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'savings',
    amount: 80000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    category: 'learning',
    amount: 5000,
    month,
    carried_over: 0,
    overspend_acknowledged: false,
    overspend_reason: null,
    manual_override: false,
    created_at: ts(),
  },
]

export const SEED_EXPENSES: Expense[] = [
  {
    id: id(),
    user_id: uid,
    amount: 120000,
    category: 'rent',
    note: 'April rent',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 4500,
    category: 'phone',
    note: null,
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 6000,
    category: 'internet',
    note: null,
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 12000,
    category: 'insurance',
    note: null,
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 12000,
    category: 'food_delivery',
    note: 'uber eats',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 2400,
    category: 'coffee',
    note: 'starbucks',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 23000,
    category: 'shopping',
    note: 'amazon + target',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 1200,
    category: 'entertainment',
    note: 'netflix',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 16000,
    category: 'personal_care',
    note: null,
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 4500,
    category: 'transport',
    note: 'uber',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 20000,
    category: 'investing',
    note: 'monthly',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    amount: 80000,
    category: 'savings',
    note: 'monthly',
    month,
    logged_at: ts(),
    created_at: ts(),
  },
]

export const SEED_REFUNDS: Refund[] = [
  {
    id: id(),
    user_id: uid,
    description: 'Amazon · blue jacket',
    amount: 2340,
    returned_at: '2026-04-22',
    expected_by: '2026-04-29',
    status: 'pending',
    resolved_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    description: 'Zara · dress',
    amount: 6700,
    returned_at: '2026-04-18',
    expected_by: '2026-04-25',
    status: 'pending',
    resolved_at: null,
    created_at: ts(),
  },
]

export const SEED_SPLITWISE: SplitwiseEntry[] = [
  {
    id: id(),
    user_id: uid,
    person: 'Riya',
    amount: 4700,
    direction: 'owed_to_me',
    description: 'dinner',
    status: 'outstanding',
    logged_at: '2026-04-08T12:00:00Z',
    settled_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    person: 'Sam',
    amount: 2350,
    direction: 'owed_to_me',
    description: 'groceries',
    status: 'outstanding',
    logged_at: '2026-04-22T12:00:00Z',
    settled_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    person: 'Priya',
    amount: 1500,
    direction: 'i_owe',
    description: 'coffee',
    status: 'outstanding',
    logged_at: '2026-04-25T12:00:00Z',
    settled_at: null,
    created_at: ts(),
  },
]

export const SEED_SUBSCRIPTIONS: Subscription[] = [
  {
    id: id(),
    user_id: uid,
    name: 'Duolingo',
    amount: 999,
    period: 'monthly',
    renewal_day: 2,
    status: 'active',
    cancelled_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Spotify',
    amount: 999,
    period: 'monthly',
    renewal_day: 8,
    status: 'active',
    cancelled_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Netflix',
    amount: 1599,
    period: 'monthly',
    renewal_day: 12,
    status: 'active',
    cancelled_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'iCloud',
    amount: 299,
    period: 'monthly',
    renewal_day: 1,
    status: 'active',
    cancelled_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Calm',
    amount: 1499,
    period: 'monthly',
    renewal_day: 20,
    status: 'active',
    cancelled_at: null,
    created_at: ts(),
  },
]

export const SEED_ACCOUNTS: Account[] = [
  {
    id: id(),
    user_id: uid,
    name: 'Chase checking',
    type: 'checking',
    last_four: '4521',
    label: 'primary',
    due_date: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Marcus HYSA',
    type: 'savings',
    last_four: '8834',
    label: 'emergency fund',
    due_date: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Fidelity 401k',
    type: 'investing',
    last_four: '2291',
    label: 'employer',
    due_date: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Robinhood',
    type: 'investing',
    last_four: '9012',
    label: 'personal',
    due_date: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Chase Sapphire',
    type: 'credit_card',
    last_four: '4821',
    label: null,
    due_date: 15,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Amex Gold',
    type: 'credit_card',
    last_four: '3341',
    label: null,
    due_date: 22,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Discover',
    type: 'credit_card',
    last_four: '7823',
    label: null,
    due_date: 8,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'Venmo',
    type: 'other',
    last_four: null,
    label: 'linked to Chase',
    due_date: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    name: 'HSA',
    type: 'other',
    last_four: '4421',
    label: 'employer',
    due_date: null,
    created_at: ts(),
  },
]

export const SEED_TODOS: FinanceTodo[] = [
  {
    id: id(),
    user_id: uid,
    description: 'Dispute Uber charge · $12 · Apr 14',
    account_id: null,
    amount: 1200,
    status: 'todo',
    completed_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    description: 'Download Chase statement · March',
    account_id: null,
    amount: null,
    status: 'todo',
    completed_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    description: 'Check HSA contribution posted',
    account_id: null,
    amount: null,
    status: 'todo',
    completed_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    description: 'File FSA receipt · dentist · $340',
    account_id: null,
    amount: 34000,
    status: 'todo',
    completed_at: null,
    created_at: ts(),
  },
  {
    id: id(),
    user_id: uid,
    description: 'Call Amex · annual fee waiver',
    account_id: null,
    amount: null,
    status: 'todo',
    completed_at: null,
    created_at: ts(),
  },
]
